version: '3.1'

services:
  vuestroapellidobd:   # Nombre del servicio cambiado a vuestro apellido
    image: mariadb:10
    container_name: sanchezbd   # Nombre del contenedor especificado
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=manager
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306  # Exponer puerto 3306 de MariaDB

volumes:
  data:
