version: '3'

networks:
  ldap_network:
    driver: bridge

services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      LDAP_BASE_DN: "dc=sanchez,dc=org"          # Change base DN
      LDAP_ORGANISATION: "Sanchez Organization"   # Change organization name
      LDAP_DOMAIN: "sanchez.org"                 # Change domain name
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"                          # Deactivate TLS for the LDAP server
    networks:
      - ldap_network
    ports:
      - "389:389"                               # Default port for unsecured LDAP
    command: --copy-service
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"               # Deactivate HTTPS
    networks:
      - ldap_network
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - openldap
